### ISSUE TITLE
Is it right ? about diffuse noise model in mvdr

### ISSUE THREAD

**Issue by bbyuan3** [donchev7/MatlabCode#1]
I checked some papers about diffuse noise model 
it should be  SINC( 2*pi*f / 340 * DR)
but i can not find any pi in your code : line 238, sim_system.m
 beta = 2*(l-1)/N*fs/340;

is there some wrong ? or I miss something ?

**Comment by donchev7** [comment]
Hi, the computations are done in the frequency domain thus the calculation is correct.
